# Generated by Django 5.2 on 2025-04-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='titulo_profesional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
