# Generated by Django 5.2 on 2025-04-10 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id_correspondencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('paginas', models.IntegerField()),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='en_revision', max_length=20)),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DocEntrante',
            fields=[
                ('id_doc_entrante', models.AutoField(primary_key=True, serialize=False)),
                ('nro_registro', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_entrantes', to='correspondencia.correspondencia')),
            ],
        ),
        migrations.CreateModel(
            name='DocInterno',
            fields=[
                ('id_doc_interno', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(editable=False)),
                ('gestion', models.PositiveIntegerField(default=2025, editable=False)),
                ('cite', models.CharField(blank=True, max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_internos', to='correspondencia.correspondencia')),
            ],
        ),
        migrations.CreateModel(
            name='DocSaliente',
            fields=[
                ('id_doc_saliente', models.AutoField(primary_key=True, serialize=False)),
                ('cite', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('fecha_seguimiento', models.DateTimeField(blank=True, null=True)),
                ('archivo_word', models.FileField(blank=True, null=True, upload_to='documentos_borrador/')),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_salientes', to='correspondencia.correspondencia')),
            ],
        ),
    ]
