# Generated by Django 5.2 on 2025-04-21 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
        ('correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacto.contacto'),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondencia',
            name='paginas',
            field=models.IntegerField(default=1),
        ),
    ]
