# Generated by Django 5.2 on 2025-04-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0002_correspondencia_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='tipo',
            field=models.CharField(choices=[('recibido', 'Recibido'), ('enviado', 'Enviado')], default='recibido', max_length=10),
        ),
    ]
