# Generated by Django 5.2 on 2025-04-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0003_correspondencia_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='tipo',
            field=models.CharField(choices=[('recibido', 'Recibido'), ('enviado', 'Enviado')], max_length=10),
        ),
    ]
