# Generated by Django 5.2 on 2025-04-22 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0004_alter_correspondencia_tipo'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.customuser'),
        ),
    ]
