# Generated by Django 5.2 on 2025-04-22 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0005_correspondencia_usuario'),
        ('documento', '0007_tipodocumentointerno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docinterno',
            name='correspondencia',
        ),
        migrations.AddField(
            model_name='docinterno',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docInterno', to='documento.tipodocumentointerno'),
        ),
    ]
