# Generated by Django 5.2 on 2025-04-10 04:32

import django.contrib.postgres.fields
import django.db.models.deletion
import documento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_documento', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_documento', models.CharField(blank=True, max_length=255)),
                ('archivo', models.FileField(upload_to=documento.models.ruta_archivo)),
                ('tipo', models.CharField(choices=[('enviado', 'Enviado'), ('recibido', 'Recibido')], max_length=10)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('correspondencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='correspondencia.correspondencia')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='documento.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='vectorDocumento',
            fields=[
                ('id_vector', models.AutoField(primary_key=True, serialize=False)),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vectores', to='documento.documento')),
            ],
        ),
    ]
