# Generated by Django 5.2 on 2025-04-10 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0001_initial'),
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='correspondencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='correspondencia.correspondencia'),
        ),
    ]
