# Generated by Django 5.2 on 2025-04-21 20:00

import documento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0004_alter_documento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=documento.models.ruta_archivo),
        ),
    ]
