# Generated by Django 5.2 on 2025-04-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0005_alter_documento_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='tipo',
        ),
    ]
