# Generated by Django 5.2 on 2025-04-22 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0006_remove_documento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoInterno',
            fields=[
                ('id_tipo_documento_interno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_documento_interno', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento_interno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_internos', to='documento.tipodocumentointerno'),
        ),
    ]
